[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[functions.environment]
  MPESA_CONSUMER_KEY = ""
  MPESA_CONSUMER_SECRET = ""
  MPESA_BUSINESS_SHORTCODE = ""
  MPESA_PASSKEY = ""
  MPESA_CALLBACK_URL = ""
  BUTTONDOWN_API_KEY = ""

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200